# Site settings
title: The Blackwater Moor
header-img: img/home-bg.png
email: davidholtonhpc@gmail.com
copyright_name: Metal-Milonga
description: > # this means to ignore newlines until "baseurl:"
  Just trying to keep my head above water..
baseurl: "" # the subpath of your site, e.g. /blog
twitter_username: LinuxArcanum
github_username:  Metal-Milonga
learn_profile: Metal-Milonga
email_username: davidholtonhpc@gmail.com

# Build settings
markdown: kramdown
highlighter: rouge
permalink: pretty
paginate: 5
exclude: ["less","node_modules","Gruntfile.js","package.json","README.md"]

gems: [jekyll-paginate, jekyll-feed]
